[package]
name = "solana-massmail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "~0.4.21"
solana-client = "^1.16"
solana-sdk = "^1.16"
thiserror = "~1.0.60"
